server:
  port: 8081

spring:
  application:
    name: ib-cc-crm-hub-int-security-mgt-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: /var/log/app/security-mgt.log
